### ISSUE TITLE
country of origin Media

### ISSUE THREAD

**Issue by HuguesPecout** [geomedia/rssaggregate#5]
L'orsque l'on branche un nouveau flux à la base de données, on doit tout d'abords enregistrer le média qui le produit. On doit alors renseigner plusieurs information sur ce média : Nom, code, URL, périodicité... et son pays d'origine. 
Le pays d'origine du média est utilisé dans la construction du "nom cod" du flux. Ex : en_CHN_chinad_int  (CHN = Chine). Cependant, cerains média ne sont pas vraiment localisables (sièges dans plusieurs pays, média purplayer difficilement localisable). Dans ce cas, je ne précise aucun pays en particulier :
![capture](https://cloud.githubusercontent.com/assets/13257120/8600077/48c7f22c-2664-11e5-83a3-6b3722a957ba.PNG)
Et le problème c'est que dans ce cas, l'application me crée un code à 2 lettres et non 3 (come CHN, FRA ou USA...), ex : en_XX_africa_gen.
Ce ne pas trés grave mais on est obligé remodifier ce "nom code" de flux aprés chaque extraction pour faire tourner nos programmes R de traitement des données... donc pas trés pratique et je suis sur que ca prend 2 min à modifier !

**Comment by dosimont** [comment]
J'ai modifié ça dans la version de dev. A savoir: il est possible de se baser sur les underscores (ou n'importe quel autre symbole) pour délimiter les différents champs plutôt que de compter le nombre de lettres.

**Comment by dosimont** [comment]
J'ai modifié ça dans la version de dev. A savoir: il est possible de se baser sur les underscores (ou n'importe quel autre symbole) pour délimiter les différents champs plutôt que de compter le nombre de lettres.
